### ISSUE TITLE
Label size

### ISSUE THREAD

**Issue by silvio-e** [KimPaow/sanity-color-list#1]
Hey, thanks for creating and sharing this plugin! :)

I have a request - in the screenshot you see that the labels for the color lists are quite big in comparison to labels at the same place in hierarchy further up on the screenshot ("Page keywords"). Would it be possible to get the labels to adjust regarding the hierarchy?

<img width="248" alt="Bildschirmfoto 2019-11-28 um 09 07 36" src="https://user-images.githubusercontent.com/3109921/69788455-d6988680-11be-11ea-8bd4-2610897c94bf.png">

**Comment by KimPaow** [comment]
@silvio-e I will add this to the todo!

**Comment by KimPaow** [comment]
@silvio-e If you run an update now this should behave as expected! Thanks for reporting this.

**Comment by silvio-e** [comment]
Awesome! Looks great! Thanks a lot! :)
