### ISSUE TITLE
Visibility for very light colors

### ISSUE THREAD

**Issue by silvio-e** [KimPaow/sanity-color-list#2]
I have some colors which are very light and they get quite difficult to spot regarding which is selected. You see it in the screenshots. 

<img width="225" alt="Bildschirmfoto 2019-12-05 um 11 11 59" src="https://user-images.githubusercontent.com/3109921/70225867-24c60080-1750-11ea-823d-f3f2e92a15b6.png">

I don't have really a suggestion, but perhaps keeping the circle a bit darker would help. What do you think?

**Comment by KimPaow** [comment]
@silvio-e Hi. Yes i've anticipated this problem as well. 

I have laid a foundation for solving this problem by adding some code that gets the brightness of colors as a value. This code is already available in the plugin but I have yet to implement it fully, as I haven't decided how to present colors that are low in contrast. Perhaps lowering the brightness of the outer circle is the way to go like you suggested. 

I'm also thinking of setting a contrast threshold and then mark the inner circle of low contrast colors. Perhaps in the same way that white is currently being presented. 

Either way I will try to publish an update for this during the coming weekend :)

**Comment by KimPaow** [comment]
@silvio-e This has been included in the new package release v1.2.0
