### ISSUE TITLE
Deselecting colors

### ISSUE THREAD

**Issue by silvio-e** [KimPaow/sanity-color-list#3]
Hei again! :) I have one more feedback :) I noticed that colors can't be deselected once one of them is selected. Clicking the selected one for deselecting would be really great or perhaps a default "none" or "transparent" color.

I noticed also that clicking the selected one would cause the document to change status to draft - means even no new color got selected.

Btw. using your plugin in production - thanks a lot again for making and sharing it! :)

**Comment by KimPaow** [comment]
Good points overall, I will try to think of something!

Thanks for the great feedback, and glad to hear you're finding good use for it :)

**Comment by KimPaow** [comment]
@silvio-e I've just published a new package which resolves this. You can now click colors again to deselect. Would be great if you would try it and let me know how it goes, I did a pretty big overhaul of the whole package and added some new options. No breaking changes but I would sleep a lot better if could get another confirmation that everything works as intended for you :)

**Comment by silvio-e** [comment]
Hey Kim! Awesome!! Just tested it and it seems to work as intended! This and the decorator contrast make it now even more fun and also easier to use! Thanks a lot!! :)
