### ISSUE TITLE
Doesn't work inside an array

### ISSUE THREAD

**Issue by j0hnm4r5** [KimPaow/sanity-color-list#6]
Unfortunately I can't get this to work when using it inside of an array (outside of an array works great).

For example:

```js
...
{
    title: `Cover`,
    name: `cover`,
    type: `array`,
    description: `The background for the card.`,
    of: [
        {
            type: `image`,
            options: { sources: [Default, Unsplash] },
        },
        {
            type: `colors`,
            options: {
                list: [
                    { title: `Red`, value: `#f16d70` },
                    { title: `Teal`, value: `#88c6db` },
                ],
            },
        },
    ],
},
...
```

returns an `Uncaught Error: Invalid item type: "[object Object]". Default array input can only contain objects (for now)` error.

**Comment by KimPaow** [comment]
Is your array with the name 'cover' a child of another array by any chance? Sanity does not support multidimensional arrays (for now) :)

**Comment by j0hnm4r5** [comment]
Nope! It is a root object inside the fields array in a root document. Like this:

```
export default createSchema({
  name: `default`,
  types: schemaTypes.concat([
    {
      name: `question`,
      type: `document`,
      fields: [
        {
          name: `cover`,
          type: `array`,
          of: [
            {
              type: `colors`,
              options: {
                list: [
                  { title: `Red`, value: `#f16d70` },
                  { title: `Teal`, value: `#88c6db` },
                  { title: `Purple`, value: `#aca0cc` },
                ],
              },
            },
          ],
        },
      ],
    },
  ]),
});

```

**Comment by j0hnm4r5** [comment]
This issue mentions this exact error: https://github.com/sanity-io/sanity/issues/452

This may be a problem with Sanity itself not supporting nested arrays.

**Comment by j0hnm4r5** [comment]
And this pull request mentioned wrapping the schema in an object: https://github.com/sanity-io/sanity/pull/1614

At face value, that seems like it might work. Instead of the plugin returning an array, it could return an object that contains an array.

**Comment by KimPaow** [comment]
Hmm, i will have to get my test studio up and running to try this out properly. But I feel like the problem shouldnt be with the plugin but rather with something else, since the type of the colors object is a string - not an array. 

Could you try wrapping the colors fields in an object and see if that solves it? 
If that doesnt solve it this issue is most likely unrelated to this plugin.

**Comment by KimPaow** [comment]
Closing this because of inactiveness, let me know if this is still an issue.
