### ISSUE TITLE
Choose to return title as well (Feature request)

### ISSUE THREAD

**Issue by heggemsnes** [KimPaow/sanity-color-list#7]
Hi

Great and clean plugin. It would be useful for me to return the title field in the query so it can be used for CSS classes like bg-${color.title}.

**Comment by KimPaow** [comment]
Good point! The title field fills no function right now except being cumbersome to fill in :) will try to fix this asap.

As always, PR's are more than welcome as well!

**Comment by heggemsnes** [comment]
Thanks a bunck!

Give me a year and maybe I will be able to do it myself and create a PR :)

**Comment by KimPaow** [comment]
This has been added to 2.0.0 and is now available 👍
